name: backstreets_widgets
version: 0.7.0
description: A package of useful widgets.
repository: https://github.com/chrisnorman7/backstreets_widgets

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.1.0-0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
